services:
  db:
    image: ghcr.io/antoinefink/postgresql-hll:16-alpine
    environment:
      POSTGRES_DB: potato
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: potato
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d potato" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
